### ndarray 的其他创建方式

In [2]:
import numpy as np

In [5]:
#arrange函数：类似于python的range函数，通过指定开始值、终值和步长来创建一维数组，注意数组不包括[终值]，
np_arange = np.arange(3,18,3)
np_arange

array([ 3,  6,  9, 12, 15])

In [7]:
#linspace函数：通过指定开始值、终值和元素个数来创建一维数组，可以通过endpoint关键字指定是否包括终值，缺省设置是包括终值
np_lin = np.linspace(0,2,9)
np_lin

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
#logspace函数：和linspace类似，不过它创建等比数列,使用随机数填充数组，即使用numpy.random模块的random()函数，数组所包含的的元素数量由参数决定'''
# 10的幂函数
np_log = np.logspace(0,2,3)
np_log

array([  1.,  10., 100.])

In [9]:
np_random = np.random.random((2,3,4)) #
np_random

array([[[0.29266742, 0.18734178, 0.54970835, 0.57675828],
        [0.10123435, 0.61778998, 0.36945254, 0.37628797],
        [0.73096618, 0.41541658, 0.84128018, 0.85460425]],

       [[0.62974428, 0.46476085, 0.92682658, 0.77656123],
        [0.59309619, 0.34745939, 0.33219334, 0.32526467],
        [0.82228648, 0.78149712, 0.55885263, 0.45021584]]])

In [10]:
#范围,数组形状
np_randint = np.random.randint(1,100,(2,3,4),'int64')
np_randint

array([[[82, 18,  1, 66],
        [56,  9, 92, 94],
        [33, 46, 49, 65]],

       [[71,  6, 79, 94],
        [47, 52, 19, 92],
        [85, 90, 71, 15]]], dtype=int64)

#### reshape 与 resize
- reshape 会生成一个新数组
- resize 修改原数组

In [32]:
a_arr = np.arange(0,30,2)
a_arr.size
a_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [34]:
#a_arr.reshape 就是一个新的数组
a_arr.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [33]:
a_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [30]:
a_arr.resize(15,1)
a_arr

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28]])

In [36]:
a=np.array([1,2,3])
a.shape


(3,)

In [39]:
b=np.array([[1,2,3]])
b.shape

(1, 3)

### pandas

- 导入数据库或者创建数据表

In [41]:
import pandas as pd
# df = pd.DataFrame(pd.read_csv('train_2.csv',header =1))
# df = pd.DataFrame(pd.read_excel('name.xlsx'))

df = pd.DataFrame({"id":[1001,1002,1003,1004,1005,1006],"date":pd.date_range('20130102', periods=6), "city":['Beijing ',
       'S H       ', ' guangzhou ', '   Shenzhen            ', '                  shanghai', 'Beijing '], "age":[23,44,54,32,34,32], "category":['100-A','100-B',
      '110-A','110-C','210-A','130-F'], "price":[1200,np.nan,2133,5433,np.nan,4432]}, columns =['id',
         'date','city','category','age','price'])
df

id       date                        city category  age   price
0  1001 2013-01-02                    Beijing     100-A   23  1200.0
1  1002 2013-01-03                  S H           100-B   44     NaN
2  1003 2013-01-04                  guangzhou     110-A   54  2133.0
3  1004 2013-01-05        Shenzhen                110-C   32  5433.0
4  1005 2013-01-06                    shanghai    210-A   34     NaN
5  1006 2013-01-07                    Beijing     130-F   32  4432.0

In [42]:
#1 查看数据表的维度
df.shape

(6, 6)

In [43]:
#2 查看数据表信息
df.info

<bound method DataFrame.info of      id       date                        city category  age   price
0  1001 2013-01-02                    Beijing     100-A   23  1200.0
1  1002 2013-01-03                  S H           100-B   44     NaN
2  1003 2013-01-04                  guangzhou     110-A   54  2133.0
3  1004 2013-01-05        Shenzhen                110-C   32  5433.0
4  1005 2013-01-06                    shanghai    210-A   34     NaN
5  1006 2013-01-07                    Beijing     130-F   32  4432.0>

In [45]:
#3 查看数据表概况
df.describe() 
#函数后加括号,std标准差,mean 平均数

id       age        price
count     6.000000   6.00000     4.000000
mean   1003.500000  36.50000  3299.500000
std       1.870829  10.87658  1966.638503
min    1001.000000  23.00000  1200.000000
25%    1002.250000  32.00000  1899.750000
50%    1003.500000  33.00000  3282.500000
75%    1004.750000  41.50000  4682.250000
max    1006.000000  54.00000  5433.000000

In [46]:
#4 查看数据表各列格式
df.dtypes

id                   int64
date        datetime64[ns]
city                object
category            object
age                  int64
price              float64
dtype: object

In [47]:
#5 查看单列格式
df['date'].dtype

dtype('<M8[ns]')

In [48]:
# 6检查数据表空值
df.isnull()

id   date   city  category    age  price
0  False  False  False     False  False  False
1  False  False  False     False  False   True
2  False  False  False     False  False  False
3  False  False  False     False  False  False
4  False  False  False     False  False   True
5  False  False  False     False  False  False

In [49]:
# 7 检查特定列空值
df['price'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: price, dtype: bool

In [51]:
# 8 查看city列中的唯一值
df['city'].unique()

array(['Beijing ', 'S H       ', ' guangzhou ', '   Shenzhen            ',
       '                  shanghai'], dtype=object)

In [52]:
# 9 查看数据表的值
df.values

array([[1001, Timestamp('2013-01-02 00:00:00'), 'Beijing ', '100-A', 23,
        1200.0],
       [1002, Timestamp('2013-01-03 00:00:00'), 'S H       ', '100-B',
        44, nan],
       [1003, Timestamp('2013-01-04 00:00:00'), ' guangzhou ', '110-A',
        54, 2133.0],
       [1004, Timestamp('2013-01-05 00:00:00'),
        '   Shenzhen            ', '110-C', 32, 5433.0],
       [1005, Timestamp('2013-01-06 00:00:00'),
        '                  shanghai', '210-A', 34, nan],
       [1006, Timestamp('2013-01-07 00:00:00'), 'Beijing ', '130-F', 32,
        4432.0]], dtype=object)

In [53]:
# 10 查看列名称
df.columns

Index(['id', 'date', 'city', 'category', 'age', 'price'], dtype='object')

In [55]:
# 11 显示前N行，默认前10行
df.head(2)

id       date        city category  age   price
0  1001 2013-01-02    Beijing     100-A   23  1200.0
1  1002 2013-01-03  S H           100-B   44     NaN

In [57]:
# 12 查看最后3行
df.tail(3)

id       date                        city category  age   price
3  1004 2013-01-05        Shenzhen                110-C   32  5433.0
4  1005 2013-01-06                    shanghai    210-A   34     NaN
5  1006 2013-01-07                    Beijing     130-F   32  4432.0

### 数据清洗

In [58]:
# 删除数据表中含有空值的行

# df = df.dropna(how = 'any')  # 改动需要重新赋值
df.dropna(how = 'any') 

id       date                     city category  age   price
0  1001 2013-01-02                 Beijing     100-A   23  1200.0
2  1003 2013-01-04               guangzhou     110-A   54  2133.0
3  1004 2013-01-05     Shenzhen                110-C   32  5433.0
5  1006 2013-01-07                 Beijing     130-F   32  4432.0

In [59]:
df

id       date                        city category  age   price
0  1001 2013-01-02                    Beijing     100-A   23  1200.0
1  1002 2013-01-03                  S H           100-B   44     NaN
2  1003 2013-01-04                  guangzhou     110-A   54  2133.0
3  1004 2013-01-05        Shenzhen                110-C   32  5433.0
4  1005 2013-01-06                    shanghai    210-A   34     NaN
5  1006 2013-01-07                    Beijing     130-F   32  4432.0

In [60]:
# 使用数字0填充数据中空值
# df = df.fillna(value=0)  # 填充后需要重新赋值
df.fillna(value=0)

id       date                        city category  age   price
0  1001 2013-01-02                    Beijing     100-A   23  1200.0
1  1002 2013-01-03                  S H           100-B   44     0.0
2  1003 2013-01-04                  guangzhou     110-A   54  2133.0
3  1004 2013-01-05        Shenzhen                110-C   32  5433.0
4  1005 2013-01-06                    shanghai    210-A   34     0.0
5  1006 2013-01-07                    Beijing     130-F   32  4432.0

#### 使用prince的均值对NA进行填充

In [62]:
#使用prince的均值对NA进行填充
# print(df['price'].mean())
df['price'] = df['price'].fillna(df['price'].mean()) 
df

id       date                        city category  age   price
0  1001 2013-01-02                    Beijing     100-A   23  1200.0
1  1002 2013-01-03                  S H           100-B   44  3299.5
2  1003 2013-01-04                  guangzhou     110-A   54  2133.0
3  1004 2013-01-05        Shenzhen                110-C   32  5433.0
4  1005 2013-01-06                    shanghai    210-A   34  3299.5
5  1006 2013-01-07                    Beijing     130-F   32  4432.0

In [63]:
# 清除city字段的字符空格
# print(df.head(6))
df['city'] = df['city'].map(str.strip)   
# 字符内部的空格不会被去掉
df

id       date       city category  age   price
0  1001 2013-01-02    Beijing    100-A   23  1200.0
1  1002 2013-01-03        S H    100-B   44  3299.5
2  1003 2013-01-04  guangzhou    110-A   54  2133.0
3  1004 2013-01-05   Shenzhen    110-C   32  5433.0
4  1005 2013-01-06   shanghai    210-A   34  3299.5
5  1006 2013-01-07    Beijing    130-F   32  4432.0

In [64]:
# city列大小写转换 lower()  upper()
# print(df.head(6))
df['city'] = df['city'].str.lower()
df

id       date       city category  age   price
0  1001 2013-01-02    beijing    100-A   23  1200.0
1  1002 2013-01-03        s h    100-B   44  3299.5
2  1003 2013-01-04  guangzhou    110-A   54  2133.0
3  1004 2013-01-05   shenzhen    110-C   32  5433.0
4  1005 2013-01-06   shanghai    210-A   34  3299.5
5  1006 2013-01-07    beijing    130-F   32  4432.0

In [65]:
df['city'] = df['city'].str.upper()
df

id       date       city category  age   price
0  1001 2013-01-02    BEIJING    100-A   23  1200.0
1  1002 2013-01-03        S H    100-B   44  3299.5
2  1003 2013-01-04  GUANGZHOU    110-A   54  2133.0
3  1004 2013-01-05   SHENZHEN    110-C   32  5433.0
4  1005 2013-01-06   SHANGHAI    210-A   34  3299.5
5  1006 2013-01-07    BEIJING    130-F   32  4432.0

In [66]:
# 更改数据格式
df['price'] = df['price'].astype('int')
df['price']

0    1200
1    3299
2    2133
3    5433
4    3299
5    4432
Name: price, dtype: int32

In [67]:
# 更改列名称
df1 = df.rename(columns ={'category':'category_size'}) # 赋值
df

id       date       city category  age  price
0  1001 2013-01-02    BEIJING    100-A   23   1200
1  1002 2013-01-03        S H    100-B   44   3299
2  1003 2013-01-04  GUANGZHOU    110-A   54   2133
3  1004 2013-01-05   SHENZHEN    110-C   32   5433
4  1005 2013-01-06   SHANGHAI    210-A   34   3299
5  1006 2013-01-07    BEIJING    130-F   32   4432

In [68]:
df1

id       date       city category_size  age  price
0  1001 2013-01-02    BEIJING         100-A   23   1200
1  1002 2013-01-03        S H         100-B   44   3299
2  1003 2013-01-04  GUANGZHOU         110-A   54   2133
3  1004 2013-01-05   SHENZHEN         110-C   32   5433
4  1005 2013-01-06   SHANGHAI         210-A   34   3299
5  1006 2013-01-07    BEIJING         130-F   32   4432

In [69]:
# 删除后出现的重复值
df['city'].drop_duplicates()
df['city']

0      BEIJING
1          S H
2    GUANGZHOU
3     SHENZHEN
4     SHANGHAI
5      BEIJING
Name: city, dtype: object

#### 数据替换,赋给新的变量才能看到结果

In [74]:
#数据替换
df['city'].replace('S H','ShangHai') #赋给新的变量才能看到结果

0      BEIJING
1     ShangHai
2    GUANGZHOU
3     SHENZHEN
4     SHANGHAI
5      BEIJING
Name: city, dtype: object

In [72]:
#数据替换
df_replace=df['city'].replace('S H','ShangHai')
df_replace

0      BEIJING
1     ShangHai
2    GUANGZHOU
3     SHENZHEN
4     SHANGHAI
5      BEIJING
Name: city, dtype: object

### 数据预处理