In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import classification_report   

In [8]:
data = pd.read_csv('./day8_test3_data.txt',sep='\s+')
print(data)

     outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no


In [19]:
#数据基本处理
x = data[['outlook','temperature','humidity','windy']]
y = data['play']
#数据分割
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state =8)
#创建字典特征提取器
transfer = DictVectorizer(sparse=False)
#字典特征提取
x_train =transfer.fit_transform(x_train.to_dict(orient='records'))
x_test =transfer.fit_transform(x_test.to_dict(orient='records'))
print(x_test)
print(transfer.get_feature_names())


[[0. 1. 0. 1. 0. 1. 1.]
 [1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1. 0. 0.]]
['humidity=high', 'humidity=normal', 'outlook=overcast', 'outlook=sunny', 'temperature=hot', 'temperature=mild', 'windy']


In [21]:
#4机器学习,模型训练
estimator = DecisionTreeClassifier()
estimator.fit(x_train,y_train)


#5模型评估
# y_pred = estimator.predict(x_test)
# print(y_pred)

#获取准确率
# score =estimator.score(x_test,y_test)
# print('准确率:',score)
#精确率precision,召回率recall
# rs = classification_report(y_true =y_test,y_pred=y_pred)
# print(rs)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split


def outlook_type(s):
    it = {'sunny': 1, 'overcast': 2, 'rainy': 3}
    return it.get(s)


def temperature(s):
    it = {'hot': 1, 'mild': 2, 'cool': 3}
    return it.get(s)


def humidity(s):
    it = {'high': 1, 'normal': 0}
    return it.get(s)


def windy(s):
    it = {'TRUE': 1, 'FALSE': 0}
    return it.get(s)


def play_type(s):
    it = {'yes': 1, 'no': 0}
    return it.get(s)


play_feature_E = 'outlook', 'temperature', 'humidity', 'windy'
play_class = 'yes', 'no'

# 1、读入数据，并将原始数据中的数据转换为数字形式
d = windy("TRUE")
# print(d)
data = np.loadtxt("playtennies.txt", delimiter=" ", dtype=str,
                  converters={1: outlook_type, 2: temperature, 3: humidity, 4: windy, 5: play_type}, encoding="UTF-8")
# print(data)

# 将数据划分为特征值和目标值
index, x, y = np.split(data, (1, 5,), axis=1)

# 2、拆分训练数据与测试数据，为了进行交叉验证
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

# 3、使用信息熵作为划分标准，对决策树进行训练
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf.fit(x_train, y_train)

# 系数反映每个特征的影响力。越大表示该特征在分类中起到的作用越大
print("每个特征的影响力:\n", clf.feature_importances_)

# 4、使用训练数据预测，预测结果完全正确
answer_pre = clf.predict(x_train)
y_train = y_train.reshape(-1)
print("训练集预测结果:\n", answer_pre)
print("训练集真实结果:\n", y_train)

# 5、对测试数据进行预测，准确度较低，说明过拟合
answer_test = clf.predict(x_test)
y_test = y_test.reshape(-1)
print("测试集预测结果:\n", answer_test)
print("测试集真实结果:\n", y_test)

ValueError: could not convert string to float: 'mild'