### 分别使用决策树, 随机森林, KNN算法, 并使用网格搜索和交叉验证对参数进行调优; 得到一个最佳的算法模型.

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import classification_report   

#### 决策树

In [4]:
#1,加载数据
data = pd.read_csv("./UCI_Credit_Card.csv")
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [7]:
#看是否有空值
print(np.any(data.isnull()))

False


In [9]:
x = data[['LIMIT_BAL','SEX','EDUCATION','MARRIAGE','AGE','PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6',
           'BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6'
           ,'PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']]
y= data['default.payment.next.month']


#2.3数据分割
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state = 8)

#3特征工程(特征提取,字典特征提取)
# x_train.to_dict(orient='records')#把数据转换为字典格式
#创建字典特征提取器
transfer = DictVectorizer(sparse=False)
#字典特征提取
x_train =transfer.fit_transform(x_train.to_dict(orient='records'))
x_test =transfer.fit_transform(x_test.to_dict(orient='records'))
# print(x_test)
# print(transfer.get_feature_names())

#4机器学习,模型训练
estimator = DecisionTreeClassifier()
estimator.fit(x_train,y_train)



DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
#5模型评估
y_pred = estimator.predict(x_test)
# print(y_pred)

#获取准确率
score =estimator.score(x_test,y_test)
print('准确率:',score)
#精确率precision,召回率recall
rs = classification_report(y_true =y_test,y_pred=y_pred)
print(rs)

准确率: 0.7288888888888889
              precision    recall  f1-score   support

           0       0.83      0.82      0.82      6995
           1       0.40      0.42      0.41      2005

   micro avg       0.73      0.73      0.73      9000
   macro avg       0.61      0.62      0.62      9000
weighted avg       0.73      0.73      0.73      9000



#### 随机森林

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [23]:
x = data[['LIMIT_BAL','SEX','EDUCATION','MARRIAGE','AGE','PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6',
           'BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6'
           ,'PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']]
y= data['default.payment.next.month']


#2.3数据分割
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state = 8)

#3特征工程(特征提取,字典特征提取)
# x_train.to_dict(orient='records')#把数据转换为字典格式
#创建字典特征提取器
transfer = DictVectorizer(sparse=False)
#字典特征提取
x_train =transfer.fit_transform(x_train.to_dict(orient='records'))
x_test =transfer.fit_transform(x_test.to_dict(orient='records'))
# print(x_test)
# print(transfer.get_feature_names())

#4机器学习,模型训练
estimator = RandomForestClassifier()
# param_grid = {'n_estimators':[10,50,100,200,500],'max_depth':[10,20,30,40,50]}


# #交叉验证
# estimator =GridSearchCV(estimator,param_grid=param_grid,cv=5)
estimator.fit(x_train,y_train)


#5模型评估
y_pred = estimator.predict(x_test)
# print(y_pred)

#获取准确率
score =estimator.score(x_test,y_test)
print('准确率:',score)
#精确率precision,召回率recall
rs = classification_report(y_true =y_test,y_pred=y_pred)
print(rs)

c:\users\struggle6\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


准确率: 0.8071111111111111
              precision    recall  f1-score   support

           0       0.83      0.95      0.88      6995
           1       0.63      0.32      0.43      2005

   micro avg       0.81      0.81      0.81      9000
   macro avg       0.73      0.63      0.66      9000
weighted avg       0.79      0.81      0.78      9000



#### 随机森林,交叉验证

In [ ]:
#4机器学习,模型训练
estimator = RandomForestClassifier()
param_grid = {'n_estimators':[10,50,100,200,500],'max_depth':[10,20,30,40,50]}


#交叉验证
estimator =GridSearchCV(estimator,param_grid=param_grid,cv=5)
estimator.fit(x_train,y_train)


#5模型评估
y_pred = estimator.predict(x_test)
# print(y_pred)

#获取准确率
score =estimator.score(x_test,y_test)
print('准确率:',score)
#精确率precision,召回率recall
rs = classification_report(y_true =y_test,y_pred=y_pred)
print(rs)

#### KNN

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [18]:
#1,加载数据
data = pd.read_csv("./UCI_Credit_Card.csv")
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [22]:
x = data[['LIMIT_BAL','SEX','EDUCATION','MARRIAGE','AGE','PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6',
           'BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6'
           ,'PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']]
y= data['default.payment.next.month']


#2.3数据分割
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state = 8)

#机器学习 KNN+GridSearchCV
estimator =KNeighborsClassifier()

#学习:训练集特征值,训练集目标值
estimator.fit(x_train,y_train)
#模型评估
#使用模型对测试集进行预测,参数为测试集的特征值,返回为预测目标值
y_pre =estimator.predict(x_test)


#准确率
score =estimator.score(x_test,y_test)
print('准确率:',score)


准确率: 0.7517777777777778


#### KNN + 交叉验证

In [ ]:
#网格搜索和交叉验证进行参数调优
#超参数数字典
param_grid ={'n_neighbors':[3,5,7,9]}
estimator=GridSearchCV(estimator,param_grid=param_grid,cv=5)

#学习:训练集特征值,训练集目标值
estimator.fit(x_train,y_train)
#模型评估
#使用模型对测试集进行预测,参数为测试集的特征值,返回为预测目标值
y_pre =estimator.predict(x_test)


#准确率
score =estimator.score(x_test,y_test)
print('准确率:',score)
#风格搜索与交叉验证结果
print('交叉验证最好分数:',estimator.best_score_)
print('交叉验证最好的模型:',estimator.best_estimator_) #最佳模型与老师的不同
print('交叉验证的结果:\n',estimator.cv_results_)


#### key_teacher

In [24]:
# -*- coding: utf-8 -*-
# 信用卡违约率分析
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


# 数据加载
data = data = pd.read_csv('./UCI_Credit_Card.csv')
# 数据探索

# 选择有效的特征值
# 特征值, 去掉第一个ID和最后一个类别
# 注意在使用Pipeline封装后的评估器, 数据中不能有列名, 此处需要DataFrame中的values.
x = data.iloc[:, 1:-1].values
# 目标值
y = data['default.payment.next.month'].values

# 30% 作为测试集，其余作为训练集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

print(x_train)

# 构造各种分类器
classifiers = [
    # 决策树
    DecisionTreeClassifier(random_state=1, criterion='gini'),
    # 随机森林
    RandomForestClassifier(random_state=1, criterion='gini'),
    # K近邻
    KNeighborsClassifier(metric='minkowski'),
]
# 分类器名称
classifier_names = [
    'dt', # 决策树
    'rf', # 随机森林
    'knn', # K近邻
]

# 使用网格搜索时, 分类器的超参数
classifier_param_grid = [
    # Pipeline: 封装后的评估器会根据模型名称, 获取对应的超参数
    # 格式要求: 模型名__超参数名称
    {'dt__max_depth': [5, 7, 9]},    # 决策树超参数
    {'rf__n_estimators': [3, 5, 6]}, # 随机森林超参数
    {'knn__n_neighbors': [4, 6, 8]}, # knn超参数
]


# 对具体的分类器进行 GridSearchCV 参数调优
def GridSearchCV_work(pipeline, x_train, y_train, x_test, y_test, param_grid, score='accuracy'):
    rs = {}
    gridsearch = GridSearchCV(estimator=pipeline, param_grid=param_grid, scoring=score, cv=5)
    # 寻找最优的参数 和最优的准确率分数
    search = gridsearch.fit(x_train, y_train)
    print("GridSearch 最优参数：", search.best_params_)
    print("GridSearch 最优分数： %0.4lf" % search.best_score_)
    y_predict = gridsearch.predict(x_test)
    print(" 准确率 %0.4lf" % accuracy_score(y_test, y_predict))
    rs['y_predict'] = y_predict
    rs['accuracy_score'] = accuracy_score(y_test, y_predict)
    return rs

# 遍历获取模型, 模型名称, 模型超参数
for model, model_name, model_param_grid in zip(classifiers, classifier_names, classifier_param_grid):

    # 使用管道将标准化和模型封装成为为一个Pipeline评估器
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        (model_name, model)
    ])
    # print(model_param_grid)
    # 使用网格搜索与交叉验证选择模型
    result = GridSearchCV_work(pipeline, x_train, y_train, x_test, y_test, model_param_grid, score='accuracy')

[[2.0000e+04 1.0000e+00 1.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.2000e+05 1.0000e+00 2.0000e+00 ... 5.0000e+03 3.0000e+03 3.0000e+03]
 [7.0000e+04 2.0000e+00 2.0000e+00 ... 7.5500e+02 1.0290e+03 5.3030e+03]
 ...
 [5.0000e+04 1.0000e+00 2.0000e+00 ... 7.0500e+02 8.1100e+02 8.7400e+02]
 [8.0000e+04 1.0000e+00 1.0000e+00 ... 1.3780e+03 1.9942e+04 2.4180e+03]
 [3.0000e+05 1.0000e+00 2.0000e+00 ... 6.6000e+01 1.4062e+04 3.0810e+03]]
GridSearch 最优参数： {'dt__max_depth': 5}
GridSearch 最优分数： 0.8202
 准确率 0.8198
GridSearch 最优参数： {'rf__n_estimators': 6}
GridSearch 最优分数： 0.7974
 准确率 0.7988


KeyboardInterrupt: 