In [1]:
import numpy as np

In [2]:
# 生成股票涨跌数据
stock_change = np.random.normal(0, 1, (4,4))

In [3]:
stock_change

array([[ 0.00371744, -1.19577807,  0.85225409,  1.13148055],
       [ 0.42310674,  1.79957995,  0.42943803, -1.0693198 ],
       [-1.18851316, -0.16720996,  0.26586555, -1.19965619],
       [-0.15809918,  0.34508518,  0.22449777, -1.00243415]])

# 逻辑运算

In [6]:
stock_change > 0.5

array([[False, False,  True,  True],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [7]:
# 把大于0.5 改为1
stock_change[stock_change > 0.5] = 1

In [8]:
stock_change

array([[ 0.00371744, -1.19577807,  1.        ,  1.        ],
       [ 0.42310674,  1.        ,  0.42943803, -1.0693198 ],
       [-1.18851316, -0.16720996,  0.26586555, -1.19965619],
       [-0.15809918,  0.34508518,  0.22449777, -1.00243415]])

## 2 通用判断函数


In [11]:
np.all(stock_change>-1)

False

In [14]:
np.any(stock_change>0.5)

True

## 3 np.where（三元运算符）


In [15]:
np.where(stock_change>0, 1, 0)

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0]])

In [16]:
stock_change

array([[ 0.00371744, -1.19577807,  1.        ,  1.        ],
       [ 0.42310674,  1.        ,  0.42943803, -1.0693198 ],
       [-1.18851316, -0.16720996,  0.26586555, -1.19965619],
       [-0.15809918,  0.34508518,  0.22449777, -1.00243415]])

In [19]:
# 判断前四个股票前四天的涨跌幅 大于0.5并且小于1的，换为1，否则为0
# 判断前四个股票前四天的涨跌幅 大于0.5或者小于-0.5的，换为1，否则为0

np.where(np.logical_and(stock_change>0.5, stock_change<=1), 1, 0)
np.where(np.logical_or(stock_change>0.5, stock_change<-0.5), 1, 0)

array([[0, 1, 1, 1],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 0, 1]])

## 统计函数

In [20]:
stock_change

array([[ 0.00371744, -1.19577807,  1.        ,  1.        ],
       [ 0.42310674,  1.        ,  0.42943803, -1.0693198 ],
       [-1.18851316, -0.16720996,  0.26586555, -1.19965619],
       [-0.15809918,  0.34508518,  0.22449777, -1.00243415]])

In [23]:
stock_change.min(axis=1)

array([-1.19577807, -1.0693198 , -1.19965619, -1.00243415])

In [24]:
stock_change.mean(axis=1)

array([ 0.20198484,  0.19580624, -0.57237844, -0.14773759])

In [27]:
# 注意: 在对象上没有这个方法, 在np中有这个方法
np.median(stock_change, axis=1)

array([ 0.50185872,  0.42627239, -0.67786156,  0.0331993 ])

In [30]:
print('前四只股票前四天内涨幅最大{}'.format(stock_change.argmax(axis=1)))

前四只股票前四天内涨幅最大[2 1 2 1]


In [31]:
print('前四只股票前四天内跌幅最大{}'.format(stock_change.argmin(axis=1)))

前四只股票前四天内跌幅最大[1 3 3 3]


# 数组与数的运算

In [33]:
arr = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr + 1

array([[2, 3, 4, 3, 2, 5],
       [6, 7, 2, 3, 4, 2]])

In [34]:
arr / 2

array([[0.5, 1. , 1.5, 1. , 0.5, 2. ],
       [2.5, 3. , 0.5, 1. , 1.5, 0.5]])

# 数组与数组的运算

In [35]:
arr = np.array([[1,2,3], [1,2,3]])

In [36]:
a =  np.array([[1,2,3], [1,2,3]])

In [37]:
arr + a

array([[2, 4, 6],
       [2, 4, 6]])

In [46]:
b = np.array([[1,2,3]])
arr + b

array([[2, 4, 6],
       [2, 4, 6]])

In [44]:
c = np.array([1,2,3])
arr + c

array([[2, 4, 6],
       [2, 4, 6]])

In [40]:
d = np.array([3])
arr + d

array([[4, 5, 6],
       [4, 5, 6]])

In [41]:
e = np.array([[2], [4]])

In [42]:
e + arr

array([[3, 4, 5],
       [5, 6, 7]])

In [47]:
print(arr.shape)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

(2, 3)
(2, 3)
(1, 3)
(3,)
(1,)
(2, 1)


In [48]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

arr1 + arr2

ValueError: operands could not be broadcast together with shapes (2,6) (2,4) 

In [49]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[4], [6]])

arr1 + arr2

array([[ 5,  6,  7,  6,  5,  8],
       [11, 12,  7,  8,  9,  7]])

# 矩阵乘法

In [50]:
score = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [51]:
# score * [0.3, 0.7]

array([[24. , 60.2],
       [24.6, 56. ],
       [25.5, 54.6],
       [27. , 63. ],
       [25.8, 57.4],
       [24.6, 63. ],
       [23.4, 56. ],
       [27.6, 65.8]])

In [53]:
# 矩阵乘法
np.matmul(score, [0.3, 0.7])

array([84.2, 80.6, 80.1, 90. , 83.2, 87.6, 79.4, 93.4])

In [54]:
np.dot(score, [0.3, 0.7])

array([84.2, 80.6, 80.1, 90. , 83.2, 87.6, 79.4, 93.4])

In [56]:
# np.matmul(score, 2)
np.dot(score, 2)

array([[160, 172],
       [164, 160],
       [170, 156],
       [180, 180],
       [172, 164],
       [164, 180],
       [156, 160],
       [184, 188]])